name: zomato_dart
description: "A wrapper for the Zomato API that exposes dart objects."
homepage: https://github.com/akatriel/ZomatoDart
version: 1.0.0
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  http: ^0.12.0+4
