library models;

part 'category.dart';
part 'city.dart';
part 'collection.dart';
part 'cuisine.dart';
part 'establishment.dart';
part 'geocode.dart';
part 'location_detail.dart';
part 'location.dart';
part 'photo.dart';
part 'popularity.dart';
part 'res_location.dart';
part 'restaurant.dart';
part 'review_query.dart';
part 'review.dart';
part 'user_rating.dart';
part 'user.dart';
part 'dailymenu.dart';
